FROM maven as MAVEN_BUILD
RUN java -version
COPY pom.xml /build/
COPY src /build/src
WORKDIR /build/
RUN mvn clean install spring-boot:repackage

FROM openjdk

WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/desafioAtlantico-0.0.1-SNAPSHOT.jar /app/
EXPOSE 8080
ENTRYPOINT ["java","-jar","desafioAtlantico-0.0.1-SNAPSHOT.jar"]
