version: "3.3"
services:
  ldap:
    image: ldap
    build:
      context: .
      dockerfile: Dockerfile.ldap
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "techinterview.com"
      LDAP_ADMIN_PASSWORD: "123456"
    ports:
      - "389"

  app: 
    image: api
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: on-failure
    links:
      - "ldap"
    depends_on:
      - "ldap"
    ports:
      - "8080:8080"
volumes:
  my_dbdata: